# Auto-generated by enclave build — do not edit.
terraform {
  backend "s3" {
    bucket         = "dev-bitspend-server-tfstate-043673801220-us-east-1"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "dev-bitspend-server-tfstate-lock"
  }
}
