name: server
description: A gRPC server for MPC Wallet
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0
  threshold:
    path: ../threshold
  protocol:
    path: ../protocol
  hive: ^2.2.3
  http: ^1.1.0
  bitcoin_base: ^7.0.0
  blockchain_utils: ^5.4.0
  path: ^1.9.1
  synchronized: ^3.1.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.0
