name: integration
description: Integration tests for MPC Wallet (client + server with mocks)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  client:
    path: ../client
  server:
    path: ../server
  threshold:
    path: ../threshold
  protocol:
    path: ../protocol
  grpc: ^3.2.4
  protobuf: ^3.1.0
  bitcoin_base: ^7.0.0
  blockchain_utils: ^5.4.0
  hive: ^2.2.3
  fixnum: ^1.1.0

dev_dependencies:
  test: ^1.24.0
